### ISSUE TITLE
I want Generate grasps on custom objects

### ISSUE THREAD

**Issue by ChengXIZhang666** [hwjiang1510/GraspTTA#10]
hi ！
This is a very good project
but I want to use a custom object to generate a grasping posture, but I reported an error
`pybullet build time: Nov  5 2023 19:16:14
using device cuda
pybullet build time: Nov  5 2023 19:16:14
Object sample 0, pose 0, iter 0, penetration loss   0.00000, consistency loss       nan, contact loss       nan
Object sample 0, pose 0, iter 299, penetration loss   0.00000, consistency loss       nan, contact loss       nan
Traceback (most recent call last):
  File "E:\PythonProjects\GraspTTA\gen_diverse_grasp_ho3d.py", line 217, in <module>
    main(args, affordance_model, cmap_model, dataloader, device, rh_mano, rh_faces)
  File "E:\PythonProjects\GraspTTA\gen_diverse_grasp_ho3d.py", line 116, in main
    penetr_vol = intersect_vox(obj_mesh, hand_mesh, pitch=0.005)
  File "E:\PythonProjects\GraspTTA\gen_diverse_grasp_ho3d.py", line 25, in intersect_vox
    obj_vox = obj_mesh.voxelized(pitch=pitch)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\base.py", line 2567, in voxelized
    return creation.voxelize(mesh=self, pitch=pitch, method=method, **kwargs)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\voxel\creation.py", line 292, in voxelize
    return voxelizers(method, mesh=mesh, pitch=pitch, **kwargs)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\util.py", line 2284, in __call__
    return self[key](*args, **kwargs)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\constants.py", line 147, in timed
    result = method(*args, **kwargs)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\voxel\creation.py", line 41, in voxelize_subdivide
    v, f, idx = remesh.subdivide_to_size(
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\remesh.py", line 189, in subdivide_to_size
    raise ValueError("max_iter exceeded!")
ValueError: max_iter exceeded!`
I tried to modify penetr_ Vol=intersect_ Vox (obj_mesh, hand_mesh, pitch=0.005) pitch is 0.5
but i got an error that
`pybullet build time: Nov  5 2023 19:16:14
using device cuda
pybullet build time: Nov  5 2023 19:16:14
Object sample 0, pose 0, iter 0, penetration loss   0.00000, consistency loss       nan, contact loss       nan
Object sample 0, pose 0, iter 299, penetration loss   0.00000, consistency loss       nan, contact loss       nan
Traceback (most recent call last):
  File "E:\PythonProjects\GraspTTA\gen_diverse_grasp_ho3d.py", line 217, in <module>
    main(args, affordance_model, cmap_model, dataloader, device, rh_mano, rh_faces)
  File "E:\PythonProjects\GraspTTA\gen_diverse_grasp_ho3d.py", line 116, in main
    penetr_vol = intersect_vox(obj_mesh, hand_mesh, pitch=0.5)
  File "E:\PythonProjects\GraspTTA\gen_diverse_grasp_ho3d.py", line 27, in intersect_vox
    inside = hand_mesh.contains(obj_points)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\base.py", line 2975, in contains
    return self.ray.contains_points(points)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\ray\ray_triangle.py", line 173, in contains_points
    return contains_points(self, points)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\constants.py", line 147, in timed
    result = method(*args, **kwargs)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\ray\ray_util.py", line 34, in contains_points
    inside_aabb = bounds.contains(intersector.mesh.bounds, points)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\caching.py", line 141, in get_cached
    value = function(*args, **kwargs)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\base.py", line 542, in bounds
    in_mesh = self.vertices[self.referenced_vertices]
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\caching.py", line 141, in get_cached
    value = function(*args, **kwargs)
  File "F:\AnacondaEnv\grasptta\lib\site-packages\trimesh\base.py", line 1100, in referenced_vertices
    referenced[self.faces] = True
IndexError: index 0 is out of bounds for axis 0 with size 0`
How to solve this problem

**Comment by ChengXIZhang666** [comment]
I have already succeeded, but the problem now is that the generation speed is very slow. Is there a method to accelerate the generation speed through multi card reasoning

**Comment by bala1144** [comment]
How did you solve this ?
